apiVersion: v1
kind: Pod
metadata:
  name: core-k8s
  labels:
    role: just-a-pod
    app: the-pod
    organization: k8s-studies
    creator: me
spec:
  containers:
    - name: pod-container
      image: docker.io/busybox:latest
      command: ['sleep','10000']
      ports:
        - name: webapp-port
          containerPort: 80
          protocol: TCP